#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfce4-session
Version  : 4.12.1
Release  : 7
URL      : http://archive.xfce.org/src/xfce/xfce4-session/4.12/xfce4-session-4.12.1.tar.bz2
Source0  : http://archive.xfce.org/src/xfce/xfce4-session/4.12/xfce4-session-4.12.1.tar.bz2
Summary  : Xfce 4 session manager
Group    : Development/Tools
License  : GPL-2.0
Requires: xfce4-session-bin
Requires: xfce4-session-lib
Requires: xfce4-session-data
Requires: xfce4-session-locales
Requires: xfce4-session-doc
BuildRequires : iceauth-bin
BuildRequires : intltool
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libwnck-1.0)
BuildRequires : pkgconfig(libxfce4ui-1)
BuildRequires : pkgconfig(libxfce4util-1.0)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(x11)
BuildRequires : sed
Patch1: stateless.patch

%description
Session manager for the Xfce desktop environment.
Shutting down your computer using the session manager:
------------------------------------------------------
Since 4.1.5, the session manager supports only sudo(8)-based shutdown, other
method can be added by packagers if desired, just replace XfsmShutdownHelper
with your code. To be able to shutdown the computer, you must be listed
in the systems sudoers file, in particular, you must be allowed to execute
$HELPER_PATH_PREFIX/xfce4/session/xfsm-shutdown-helper as user root (where
$HELPER_PATH_PREFIX is the directory passed to configure with the
--with-helper-path-prefix option or /usr/local/lib by default).

%package bin
Summary: bin components for the xfce4-session package.
Group: Binaries
Requires: xfce4-session-data

%description bin
bin components for the xfce4-session package.


%package data
Summary: data components for the xfce4-session package.
Group: Data

%description data
data components for the xfce4-session package.


%package dev
Summary: dev components for the xfce4-session package.
Group: Development
Requires: xfce4-session-lib
Requires: xfce4-session-bin
Requires: xfce4-session-data

%description dev
dev components for the xfce4-session package.


%package doc
Summary: doc components for the xfce4-session package.
Group: Documentation

%description doc
doc components for the xfce4-session package.


%package lib
Summary: lib components for the xfce4-session package.
Group: Libraries
Requires: xfce4-session-data

%description lib
lib components for the xfce4-session package.


%package locales
Summary: locales components for the xfce4-session package.
Group: Default

%description locales
locales components for the xfce4-session package.


%prep
%setup -q -n xfce4-session-4.12.1
%patch1 -p1

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang xfce4-session
## make_install_append content
mv %{buildroot}%{_sysconfdir}/xdg %{buildroot}%{_datadir}/.
## make_install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/xfce4/session/balou-export-theme
/usr/lib64/xfce4/session/balou-install-theme
/usr/lib64/xfce4/session/splash-engines/libbalou.so
/usr/lib64/xfce4/session/splash-engines/libmice.so
/usr/lib64/xfce4/session/splash-engines/libsimple.so
/usr/lib64/xfce4/session/xfsm-shutdown-helper

%files bin
%defattr(-,root,root,-)
/usr/bin/startxfce4
/usr/bin/xfce4-session
/usr/bin/xfce4-session-logout
/usr/bin/xfce4-session-settings
/usr/bin/xflock4

%files data
%defattr(-,root,root,-)
/usr/share/applications/xfce-session-settings.desktop
/usr/share/applications/xfce4-session-logout.desktop
/usr/share/icons/hicolor/128x128/apps/xfce4-session.png
/usr/share/icons/hicolor/48x48/apps/system-hibernate.png
/usr/share/icons/hicolor/48x48/apps/system-log-out.png
/usr/share/icons/hicolor/48x48/apps/system-reboot.png
/usr/share/icons/hicolor/48x48/apps/system-shutdown.png
/usr/share/icons/hicolor/48x48/apps/system-suspend.png
/usr/share/icons/hicolor/48x48/apps/xfce4-session.png
/usr/share/icons/hicolor/48x48/apps/xfce4-splash.png
/usr/share/icons/hicolor/48x48/apps/xfsm-hibernate.png
/usr/share/icons/hicolor/48x48/apps/xfsm-logout.png
/usr/share/icons/hicolor/48x48/apps/xfsm-reboot.png
/usr/share/icons/hicolor/48x48/apps/xfsm-shutdown.png
/usr/share/icons/hicolor/48x48/apps/xfsm-suspend.png
/usr/share/icons/hicolor/scalable/apps/system-shutdown.svg
/usr/share/icons/hicolor/scalable/apps/xfce4-session.svg
/usr/share/icons/hicolor/scalable/apps/xfsm-shutdown.svg
/usr/share/themes/Default/balou/logo.png
/usr/share/themes/Default/balou/themerc
/usr/share/xdg/autostart/xscreensaver.desktop
/usr/share/xdg/xfce4/Xft.xrdb
/usr/share/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
/usr/share/xdg/xfce4/xinitrc
/usr/share/xsessions/xfce.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/xfce4/xfce4-session-4.6/libxfsm/xfsm-splash-engine.h
/usr/include/xfce4/xfce4-session-4.6/libxfsm/xfsm-splash-rc.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f xfce4-session.lang 
%defattr(-,root,root,-)

